/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adsfinalproject;

import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author kleir
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    ImageIcon darkd, darku, darko, darkp, darks, darkr;
    ImageIcon dash, user, ord, pr, sup, rep ;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        setSize(1318, 847);
        jPanel1.setVisible(true);
        setLocationRelativeTo(null);
        
        
        //----//
        darkd = new ImageIcon(getClass().getResource("/design/darkd.png"));
        darku = new ImageIcon(getClass().getResource("/design/darku.png"));
        darko = new ImageIcon(getClass().getResource("/design/darko.png"));
        darkp = new ImageIcon(getClass().getResource("/design/darkp.png"));
        darks = new ImageIcon(getClass().getResource("/design/darks.png"));
        darkr = new ImageIcon(getClass().getResource("/design/darkr.png"));
        dash = new ImageIcon(getClass().getResource("/design/Dashboard.png"));
        user = new ImageIcon(getClass().getResource("/design/users.png"));
        ord = new ImageIcon(getClass().getResource("/design/AAorder.png"));
        pr = new ImageIcon(getClass().getResource("/design/products.png"));
        sup = new ImageIcon(getClass().getResource("/design/suppliers.png"));
        rep = new ImageIcon(getClass().getResource("/design/reports.png"));
        
          //-----//
        jPanel2.setLayout(new CardLayout());
        
        jPanel2.add(pnlDashboard, "dashboard");
        jPanel2.add(pnlUsers, "users");
        jPanel2.add(pnlOrder, "order");
        jPanel2.add(pnlProduct, "product");
        jPanel2.add(pnlSuppliers, "supplier");
        jPanel2.add(pnlReports, "reports");
        
        CardLayout cl = (CardLayout)(jPanel2.getLayout());
        cl.show(jPanel2, "dashboard");
       
    }
     private void setActive(String page){
        btnDashboard.setIcon(dash);
        btnUsers.setIcon(user);
        btnOrders.setIcon(ord);
        btnProducts.setIcon(pr);
        btnSupplier.setIcon(sup);
        btnReports.setIcon(rep);
       
        
        if(page.equals("dashboard")){
            btnDashboard.setIcon(darkd);
        }else if (page.equals("users")){
            btnUsers.setIcon(darku);
        }else if (page.equals("order")){
            btnOrders.setIcon(darko);
        }else if (page.equals("product")){
            btnProducts.setIcon(darkp);
        }else if (page.equals("supplier")){
            btnSupplier.setIcon(darks);
        }else if (page.equals("reports")){
            btnReports.setIcon(darkr);
        }
            CardLayout cl = (CardLayout)(jPanel2.getLayout());
            cl.show(jPanel2, "dashboard");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUsers = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        btnProducts = new javax.swing.JButton();
        btnOrders = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlReports = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        pnlSuppliers = new javax.swing.JPanel();
        pnlAddSuppliers = new javax.swing.JPanel();
        txtAddSupCN = new javax.swing.JTextField();
        txtAddSupCP = new javax.swing.JTextField();
        txtAddName1 = new javax.swing.JTextField();
        txtAddSupEm = new javax.swing.JTextField();
        btnAddCancel1 = new javax.swing.JButton();
        btnAddSave1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pnlUsers2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnSupAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnSupEdit = new javax.swing.JButton();
        btnSupDel = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        pnlOrder = new javax.swing.JPanel();
        pnlverufy = new javax.swing.JPanel();
        btnOrdCanc = new javax.swing.JButton();
        btnOrdConf = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        pnlView = new javax.swing.JPanel();
        btnOrdCanc1 = new javax.swing.JButton();
        btnOrdConf1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnOrdView = new javax.swing.JButton();
        btnOrdDel1 = new javax.swing.JButton();
        btnOrdEdit2 = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        btnOrdView1 = new javax.swing.JButton();
        btnOrdDel2 = new javax.swing.JButton();
        btnOrdEdit3 = new javax.swing.JButton();
        jComboBox9 = new javax.swing.JComboBox<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        btnOrdVerifyPay1 = new javax.swing.JButton();
        btnOrdDel3 = new javax.swing.JButton();
        btnOrdEdit4 = new javax.swing.JButton();
        jComboBox8 = new javax.swing.JComboBox<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlUsers = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        btnCusDel = new javax.swing.JButton();
        btnCusEdit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        pnlAddStaff = new javax.swing.JPanel();
        txtAddSupCP1 = new javax.swing.JTextField();
        txtAddName2 = new javax.swing.JTextField();
        txtAddSupEm1 = new javax.swing.JTextField();
        btnAddCancel2 = new javax.swing.JButton();
        btnAddSave2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        pnlUsers1 = new javax.swing.JPanel();
        btnStaffEdit = new javax.swing.JButton();
        btnStaffDel = new javax.swing.JButton();
        btnStaffAdd = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        btnCusDel1 = new javax.swing.JButton();
        btnCusEdit1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        btnStaffAdd1 = new javax.swing.JButton();
        btnStaffDel1 = new javax.swing.JButton();
        btnStaffEdit1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        lblLowStiock = new javax.swing.JLabel();
        lblTotalCustomer = new javax.swing.JLabel();
        lblTotalSales = new javax.swing.JLabel();
        lblTransPend = new javax.swing.JLabel();
        lblTotalOrd = new javax.swing.JLabel();
        lblTransComp = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pnlProduct = new javax.swing.JPanel();
        pnlAddPr = new javax.swing.JPanel();
        txtAddName = new javax.swing.JTextField();
        txtAddCategory = new javax.swing.JTextField();
        txtxAddDescrip = new javax.swing.JTextField();
        txtAddPrice = new javax.swing.JTextField();
        txtAddStock = new javax.swing.JTextField();
        btnAddCancel = new javax.swing.JButton();
        btnAddSave = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        pnlRestock = new javax.swing.JPanel();
        jTextField17 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnAddStock1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnPrDel = new javax.swing.JButton();
        btnPrRestock = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnPrUpdate1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(285, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/users.png"))); // NOI18N
        btnUsers.setBorder(null);
        btnUsers.setBorderPainted(false);
        btnUsers.setContentAreaFilled(false);
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 360, 70));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/logout.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 700, 300, 50));

        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/reports.png"))); // NOI18N
        btnReports.setBorder(null);
        btnReports.setBorderPainted(false);
        btnReports.setContentAreaFilled(false);
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        jPanel1.add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 300, 70));

        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/suppliers.png"))); // NOI18N
        btnSupplier.setBorder(null);
        btnSupplier.setBorderPainted(false);
        btnSupplier.setContentAreaFilled(false);
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(btnSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 300, 80));

        btnProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/products.png"))); // NOI18N
        btnProducts.setBorder(null);
        btnProducts.setBorderPainted(false);
        btnProducts.setContentAreaFilled(false);
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });
        jPanel1.add(btnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 300, 70));

        btnOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/AAorder.png"))); // NOI18N
        btnOrders.setBorder(null);
        btnOrders.setBorderPainted(false);
        btnOrders.setContentAreaFilled(false);
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 320, 80));

        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Dashboard.png"))); // NOI18N
        btnDashboard.setBorder(null);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 300, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/admindasd.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 780));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 250, 850));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        pnlReports.setBackground(new java.awt.Color(255, 255, 255));
        pnlReports.setPreferredSize(new java.awt.Dimension(1300, 800));
        pnlReports.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane4.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane4.setToolTipText("");
        jTabbedPane4.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setBackground(new java.awt.Color(255, 255, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Total Order", "Total Sales"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 167, 930, 540));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/SalesReports.png"))); // NOI18N
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1277, -1));

        jTabbedPane4.addTab("S", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        jTable4.setBackground(new java.awt.Color(255, 255, 255));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Name", "Stock Quantity", "Status"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel9.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 167, 930, 540));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/InventoryReports.png"))); // NOI18N
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        jTabbedPane4.addTab("I", jPanel9);

        pnlReports.add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 800));

        jPanel2.add(pnlReports, "reports");
        pnlReports.getAccessibleContext().setAccessibleName("");

        pnlSuppliers.setBackground(new java.awt.Color(255, 255, 255));
        pnlSuppliers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAddSuppliers.setBackground(new java.awt.Color(255, 255, 255));
        pnlAddSuppliers.setPreferredSize(new java.awt.Dimension(510, 680));
        pnlAddSuppliers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAddSupCN.setBackground(new java.awt.Color(255, 255, 255));
        txtAddSupCN.setForeground(new java.awt.Color(0, 0, 0));
        txtAddSupCN.setBorder(null);
        pnlAddSuppliers.add(txtAddSupCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 350, 30));

        txtAddSupCP.setBackground(new java.awt.Color(255, 255, 255));
        txtAddSupCP.setForeground(new java.awt.Color(0, 0, 0));
        txtAddSupCP.setBorder(null);
        pnlAddSuppliers.add(txtAddSupCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 370, 30));

        txtAddName1.setBackground(new java.awt.Color(255, 255, 255));
        txtAddName1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtAddName1.setForeground(new java.awt.Color(0, 0, 0));
        txtAddName1.setBorder(null);
        txtAddName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddName1ActionPerformed(evt);
            }
        });
        pnlAddSuppliers.add(txtAddName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 360, 30));

        txtAddSupEm.setBackground(new java.awt.Color(255, 255, 255));
        txtAddSupEm.setForeground(new java.awt.Color(0, 0, 0));
        txtAddSupEm.setBorder(null);
        pnlAddSuppliers.add(txtAddSupEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 360, 30));

        btnAddCancel1.setText("-");
        btnAddCancel1.setBorder(null);
        btnAddCancel1.setBorderPainted(false);
        btnAddCancel1.setContentAreaFilled(false);
        btnAddCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCancel1ActionPerformed(evt);
            }
        });
        pnlAddSuppliers.add(btnAddCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 80, 40));

        btnAddSave1.setText("-");
        btnAddSave1.setBorder(null);
        btnAddSave1.setBorderPainted(false);
        btnAddSave1.setContentAreaFilled(false);
        pnlAddSuppliers.add(btnAddSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 80, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/AddSupplier.png"))); // NOI18N
        pnlAddSuppliers.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlSuppliers.add(pnlAddSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        pnlUsers2.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsers2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        jTable5.setBackground(new java.awt.Color(255, 255, 255));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact Person", "Contact No.", "Email", "Status"
            }
        ));
        jScrollPane5.setViewportView(jTable5);
        if (jTable5.getColumnModel().getColumnCount() > 0) {
            jTable5.getColumnModel().getColumn(4).setResizable(false);
            jTable5.getColumnModel().getColumn(5).setHeaderValue("Status");
        }

        pnlUsers2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 167, 930, 500));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Active", "Inactive" }));
        pnlUsers2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 112, 150, 30));

        btnSupAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnSupAdd.setText("-");
        btnSupAdd.setBorder(null);
        btnSupAdd.setBorderPainted(false);
        btnSupAdd.setContentAreaFilled(false);
        btnSupAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupAddActionPerformed(evt);
            }
        });
        pnlUsers2.add(btnSupAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 740, 110, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Supplier.png"))); // NOI18N
        pnlUsers2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, -1));

        btnSupEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnSupEdit.setText("-");
        btnSupEdit.setBorder(null);
        btnSupEdit.setBorderPainted(false);
        btnSupEdit.setContentAreaFilled(false);
        pnlUsers2.add(btnSupEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 740, 70, 30));

        btnSupDel.setBackground(new java.awt.Color(255, 255, 255));
        btnSupDel.setText("-");
        btnSupDel.setBorder(null);
        btnSupDel.setBorderPainted(false);
        btnSupDel.setContentAreaFilled(false);
        pnlUsers2.add(btnSupDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 740, 80, 30));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(null);
        pnlUsers2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 112, 380, 20));

        pnlSuppliers.add(pnlUsers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(pnlSuppliers, "suppliers");

        pnlOrder.setBackground(new java.awt.Color(255, 255, 255));
        pnlOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlverufy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrdCanc.setText("-");
        btnOrdCanc.setBorder(null);
        btnOrdCanc.setBorderPainted(false);
        btnOrdCanc.setContentAreaFilled(false);
        btnOrdCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdCancActionPerformed(evt);
            }
        });
        pnlverufy.add(btnOrdCanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 90, 30));

        btnOrdConf.setText("-");
        btnOrdConf.setBorder(null);
        btnOrdConf.setBorderPainted(false);
        btnOrdConf.setContentAreaFilled(false);
        pnlverufy.add(btnOrdConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 90, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/apayment.png"))); // NOI18N
        pnlverufy.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 6, 380, 500));

        pnlOrder.add(pnlverufy, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 390, 510));

        pnlView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrdCanc1.setText("-");
        btnOrdCanc1.setBorder(null);
        btnOrdCanc1.setBorderPainted(false);
        btnOrdCanc1.setContentAreaFilled(false);
        btnOrdCanc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdCanc1ActionPerformed(evt);
            }
        });
        pnlView.add(btnOrdCanc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 90, 30));

        btnOrdConf1.setText("-");
        btnOrdConf1.setBorder(null);
        btnOrdConf1.setBorderPainted(false);
        btnOrdConf1.setContentAreaFilled(false);
        pnlView.add(btnOrdConf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 90, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/aorder.png"))); // NOI18N
        pnlView.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 6, 380, 500));

        pnlOrder.add(pnlView, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 390, 510));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrdView.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdView.setText("-");
        btnOrdView.setBorder(null);
        btnOrdView.setBorderPainted(false);
        btnOrdView.setContentAreaFilled(false);
        btnOrdView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdViewActionPerformed(evt);
            }
        });
        jPanel4.add(btnOrdView, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 740, 130, 30));

        btnOrdDel1.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdDel1.setText("-");
        btnOrdDel1.setBorder(null);
        btnOrdDel1.setBorderPainted(false);
        btnOrdDel1.setContentAreaFilled(false);
        jPanel4.add(btnOrdDel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 740, 70, 30));

        btnOrdEdit2.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdEdit2.setText("-");
        btnOrdEdit2.setBorder(null);
        btnOrdEdit2.setBorderPainted(false);
        btnOrdEdit2.setContentAreaFilled(false);
        jPanel4.add(btnOrdEdit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 740, 70, 30));

        jTabbedPane5.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane5.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane5.setToolTipText("");
        jTabbedPane5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrdView1.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdView1.setText("-");
        btnOrdView1.setBorder(null);
        btnOrdView1.setBorderPainted(false);
        btnOrdView1.setContentAreaFilled(false);
        btnOrdView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdView1ActionPerformed(evt);
            }
        });
        jPanel12.add(btnOrdView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 740, 130, 30));

        btnOrdDel2.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdDel2.setText("-");
        btnOrdDel2.setBorder(null);
        btnOrdDel2.setBorderPainted(false);
        btnOrdDel2.setContentAreaFilled(false);
        jPanel12.add(btnOrdDel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 740, 70, 30));

        btnOrdEdit3.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdEdit3.setText("-");
        btnOrdEdit3.setBorder(null);
        btnOrdEdit3.setBorderPainted(false);
        btnOrdEdit3.setContentAreaFilled(false);
        jPanel12.add(btnOrdEdit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 740, 70, 30));

        jComboBox9.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox9.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Pending", "Preparing", "Completed" }));
        jPanel12.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 112, 190, 30));

        jScrollPane12.setBackground(new java.awt.Color(255, 255, 255));

        jTable12.setBackground(new java.awt.Color(255, 255, 255));
        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Total", "Order Type", "CustomerID", "Status"
            }
        ));
        jScrollPane12.setViewportView(jTable12);
        if (jTable12.getColumnModel().getColumnCount() > 0) {
            jTable12.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel12.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 167, 930, 500));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/orderdash.png"))); // NOI18N
        jPanel12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1277, -1));

        jTabbedPane5.addTab("O", jPanel12);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrdVerifyPay1.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdVerifyPay1.setText("-");
        btnOrdVerifyPay1.setBorder(null);
        btnOrdVerifyPay1.setBorderPainted(false);
        btnOrdVerifyPay1.setContentAreaFilled(false);
        btnOrdVerifyPay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdVerifyPay1ActionPerformed(evt);
            }
        });
        jPanel13.add(btnOrdVerifyPay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 740, 130, 30));

        btnOrdDel3.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdDel3.setText("-");
        btnOrdDel3.setBorder(null);
        btnOrdDel3.setBorderPainted(false);
        btnOrdDel3.setContentAreaFilled(false);
        jPanel13.add(btnOrdDel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 740, 70, 30));

        btnOrdEdit4.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdEdit4.setText("-");
        btnOrdEdit4.setBorder(null);
        btnOrdEdit4.setBorderPainted(false);
        btnOrdEdit4.setContentAreaFilled(false);
        jPanel13.add(btnOrdEdit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 740, 70, 30));

        jComboBox8.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox8.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Pending", "Preparing", "Completed" }));
        jPanel13.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 112, 190, 30));

        jScrollPane11.setBackground(new java.awt.Color(255, 255, 255));

        jTable11.setBackground(new java.awt.Color(255, 255, 255));
        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Order ID", "Amount", "Date", "Type", "Reference No.", "Status"
            }
        ));
        jScrollPane11.setViewportView(jTable11);
        if (jTable11.getColumnModel().getColumnCount() > 0) {
            jTable11.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel13.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 167, 930, 500));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Payment.png"))); // NOI18N
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, -1));

        jTabbedPane5.addTab("P", jPanel13);

        jPanel4.add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 800));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/orderdash.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1277, -1));

        pnlOrder.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(pnlOrder, "order");

        pnlUsers.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane2.setToolTipText("");
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox3.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox3.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status:", "Active", "Inactive" }));
        jComboBox3.setBorder(null);
        jPanel5.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 240, 30));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setBorder(null);
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 112, 370, 20));

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));

        jTable7.setBackground(new java.awt.Color(255, 255, 255));
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact No.", "Status"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        jPanel5.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 167, 930, 500));

        btnCusDel.setBackground(new java.awt.Color(255, 255, 255));
        btnCusDel.setText("-");
        btnCusDel.setBorder(null);
        btnCusDel.setBorderPainted(false);
        btnCusDel.setContentAreaFilled(false);
        jPanel5.add(btnCusDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 740, 70, 30));

        btnCusEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnCusEdit.setText("-");
        btnCusEdit.setBorder(null);
        btnCusEdit.setBorderPainted(false);
        btnCusEdit.setContentAreaFilled(false);
        jPanel5.add(btnCusEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 740, 70, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Usersimnida.png"))); // NOI18N
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1277, -1));

        jTabbedPane2.addTab("C", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAddStaff.setBackground(new java.awt.Color(255, 255, 255));
        pnlAddStaff.setPreferredSize(new java.awt.Dimension(510, 680));
        pnlAddStaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAddSupCP1.setBackground(new java.awt.Color(255, 255, 255));
        txtAddSupCP1.setForeground(new java.awt.Color(0, 0, 0));
        txtAddSupCP1.setBorder(null);
        pnlAddStaff.add(txtAddSupCP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 360, 30));

        txtAddName2.setBackground(new java.awt.Color(255, 255, 255));
        txtAddName2.setForeground(new java.awt.Color(0, 0, 0));
        txtAddName2.setBorder(null);
        pnlAddStaff.add(txtAddName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 350, 30));

        txtAddSupEm1.setBackground(new java.awt.Color(255, 255, 255));
        txtAddSupEm1.setForeground(new java.awt.Color(0, 0, 0));
        txtAddSupEm1.setBorder(null);
        pnlAddStaff.add(txtAddSupEm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 360, 30));

        btnAddCancel2.setText("-");
        btnAddCancel2.setBorder(null);
        btnAddCancel2.setBorderPainted(false);
        btnAddCancel2.setContentAreaFilled(false);
        btnAddCancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCancel2ActionPerformed(evt);
            }
        });
        pnlAddStaff.add(btnAddCancel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 90, 50));

        btnAddSave2.setText("-");
        btnAddSave2.setBorder(null);
        btnAddSave2.setBorderPainted(false);
        btnAddSave2.setContentAreaFilled(false);
        pnlAddStaff.add(btnAddSave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 90, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/AddStaff.png"))); // NOI18N
        pnlAddStaff.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 680));

        jPanel6.add(pnlAddStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        pnlUsers1.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsers1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStaffEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnStaffEdit.setText("-");
        btnStaffEdit.setBorder(null);
        btnStaffEdit.setBorderPainted(false);
        btnStaffEdit.setContentAreaFilled(false);
        pnlUsers1.add(btnStaffEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 740, 70, 30));

        btnStaffDel.setBackground(new java.awt.Color(255, 255, 255));
        btnStaffDel.setText("-");
        btnStaffDel.setBorder(null);
        btnStaffDel.setBorderPainted(false);
        btnStaffDel.setContentAreaFilled(false);
        pnlUsers1.add(btnStaffDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 740, 70, 30));

        btnStaffAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnStaffAdd.setText("-");
        btnStaffAdd.setBorder(null);
        btnStaffAdd.setBorderPainted(false);
        btnStaffAdd.setContentAreaFilled(false);
        btnStaffAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffAddActionPerformed(evt);
            }
        });
        pnlUsers1.add(btnStaffAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 740, 150, 40));

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setBorder(null);
        pnlUsers1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 112, 370, 20));

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 255));

        jTable8.setBackground(new java.awt.Color(255, 255, 255));
        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Contact No.", "Status"
            }
        ));
        jScrollPane8.setViewportView(jTable8);

        pnlUsers1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 167, 930, 500));

        jComboBox4.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox4.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Active", "On Duty", "Inactive" }));
        jComboBox4.setBorder(null);
        pnlUsers1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 240, 30));

        jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane3.setToolTipText("");
        jTabbedPane3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox5.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox5.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setBorder(null);
        jPanel10.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 240, 30));

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setBorder(null);
        jPanel10.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 112, 370, 20));

        jScrollPane9.setBackground(new java.awt.Color(255, 255, 255));

        jTable9.setBackground(new java.awt.Color(255, 255, 255));
        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact No.", "Status"
            }
        ));
        jScrollPane9.setViewportView(jTable9);

        jPanel10.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 167, 930, 500));

        btnCusDel1.setBackground(new java.awt.Color(255, 255, 255));
        btnCusDel1.setText("-");
        btnCusDel1.setBorder(null);
        btnCusDel1.setBorderPainted(false);
        btnCusDel1.setContentAreaFilled(false);
        jPanel10.add(btnCusDel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 740, 70, 30));

        btnCusEdit1.setBackground(new java.awt.Color(255, 255, 255));
        btnCusEdit1.setText("-");
        btnCusEdit1.setBorder(null);
        btnCusEdit1.setBorderPainted(false);
        btnCusEdit1.setContentAreaFilled(false);
        jPanel10.add(btnCusEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 740, 70, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Usersimnida.png"))); // NOI18N
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1277, -1));

        jTabbedPane3.addTab("C", jPanel10);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox6.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox6.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Active", "On Duty", "Inactive" }));
        jComboBox6.setBorder(null);
        jPanel11.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 240, 30));

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        jTextField6.setBorder(null);
        jPanel11.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 112, 370, 20));

        jScrollPane10.setBackground(new java.awt.Color(255, 255, 255));

        jTable10.setBackground(new java.awt.Color(255, 255, 255));
        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Contact No.", "Status"
            }
        ));
        jScrollPane10.setViewportView(jTable10);

        jPanel11.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 167, 930, 500));

        btnStaffAdd1.setBackground(new java.awt.Color(255, 255, 255));
        btnStaffAdd1.setText("-");
        btnStaffAdd1.setBorder(null);
        btnStaffAdd1.setBorderPainted(false);
        btnStaffAdd1.setContentAreaFilled(false);
        btnStaffAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffAdd1ActionPerformed(evt);
            }
        });
        jPanel11.add(btnStaffAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 740, 150, 40));

        btnStaffDel1.setBackground(new java.awt.Color(255, 255, 255));
        btnStaffDel1.setText("-");
        btnStaffDel1.setBorder(null);
        btnStaffDel1.setBorderPainted(false);
        btnStaffDel1.setContentAreaFilled(false);
        jPanel11.add(btnStaffDel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 740, 70, 30));

        btnStaffEdit1.setBackground(new java.awt.Color(255, 255, 255));
        btnStaffEdit1.setText("-");
        btnStaffEdit1.setBorder(null);
        btnStaffEdit1.setBorderPainted(false);
        btnStaffEdit1.setContentAreaFilled(false);
        jPanel11.add(btnStaffEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 740, 70, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Userdash.png"))); // NOI18N
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, -1));

        jTabbedPane3.addTab("S", jPanel11);

        pnlUsers1.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 800));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Userdash.png"))); // NOI18N
        pnlUsers1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, -1));

        jPanel6.add(pnlUsers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.addTab("S", jPanel6);

        pnlUsers.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 800));

        jPanel2.add(pnlUsers, "users");

        pnlDashboard.setBackground(new java.awt.Color(255, 255, 255));
        pnlDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLowStiock.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLowStiock.setForeground(new java.awt.Color(255, 255, 255));
        lblLowStiock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLowStiock.setText("-");
        pnlDashboard.add(lblLowStiock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 140, 70, -1));

        lblTotalCustomer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalCustomer.setText("-");
        pnlDashboard.add(lblTotalCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, 70, -1));

        lblTotalSales.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalSales.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalSales.setText("-");
        pnlDashboard.add(lblTotalSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 50, -1));

        lblTransPend.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTransPend.setForeground(new java.awt.Color(0, 0, 0));
        lblTransPend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTransPend.setText("-");
        pnlDashboard.add(lblTransPend, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 700, 100, 60));

        lblTotalOrd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalOrd.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalOrd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalOrd.setText("-");
        pnlDashboard.add(lblTotalOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 40, -1));

        lblTransComp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTransComp.setForeground(new java.awt.Color(0, 0, 0));
        lblTransComp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTransComp.setText("-");
        pnlDashboard.add(lblTransComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 700, 90, 70));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer", "Total", "Order Type", "Status", "Date"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        pnlDashboard.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 930, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/A.png"))); // NOI18N
        pnlDashboard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 810));

        jPanel2.add(pnlDashboard, "dashboard");

        pnlProduct.setBackground(new java.awt.Color(255, 255, 255));
        pnlProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAddPr.setBackground(new java.awt.Color(255, 255, 255));
        pnlAddPr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAddName.setBackground(new java.awt.Color(255, 255, 255));
        txtAddName.setForeground(new java.awt.Color(0, 0, 0));
        txtAddName.setBorder(null);
        pnlAddPr.add(txtAddName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 380, 30));

        txtAddCategory.setBackground(new java.awt.Color(255, 255, 255));
        txtAddCategory.setForeground(new java.awt.Color(0, 0, 0));
        txtAddCategory.setBorder(null);
        pnlAddPr.add(txtAddCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 380, 30));

        txtxAddDescrip.setBackground(new java.awt.Color(255, 255, 255));
        txtxAddDescrip.setForeground(new java.awt.Color(0, 0, 0));
        txtxAddDescrip.setBorder(null);
        txtxAddDescrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtxAddDescripActionPerformed(evt);
            }
        });
        pnlAddPr.add(txtxAddDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 390, 90));

        txtAddPrice.setBackground(new java.awt.Color(255, 255, 255));
        txtAddPrice.setForeground(new java.awt.Color(0, 0, 0));
        txtAddPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAddPrice.setBorder(null);
        pnlAddPr.add(txtAddPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 130, 30));

        txtAddStock.setBackground(new java.awt.Color(255, 255, 255));
        txtAddStock.setForeground(new java.awt.Color(0, 0, 0));
        txtAddStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAddStock.setBorder(null);
        pnlAddPr.add(txtAddStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 140, 30));

        btnAddCancel.setText("-");
        btnAddCancel.setBorder(null);
        btnAddCancel.setBorderPainted(false);
        btnAddCancel.setContentAreaFilled(false);
        btnAddCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCancelActionPerformed(evt);
            }
        });
        pnlAddPr.add(btnAddCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 80, 40));

        btnAddSave.setText("-");
        btnAddSave.setBorder(null);
        btnAddSave.setBorderPainted(false);
        btnAddSave.setContentAreaFilled(false);
        pnlAddPr.add(btnAddSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 80, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Add Product.png"))); // NOI18N
        pnlAddPr.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -4, 510, 690));

        pnlProduct.add(pnlAddPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 510, 680));

        pnlRestock.setBackground(new java.awt.Color(255, 255, 255));
        pnlRestock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField17.setBackground(new java.awt.Color(255, 255, 255));
        jTextField17.setForeground(new java.awt.Color(0, 0, 0));
        jTextField17.setBorder(null);
        pnlRestock.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 370, -1));

        jTextField16.setBackground(new java.awt.Color(255, 255, 255));
        jTextField16.setForeground(new java.awt.Color(0, 0, 0));
        jTextField16.setBorder(null);
        pnlRestock.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 370, 20));

        jTextField15.setBackground(new java.awt.Color(255, 255, 255));
        jTextField15.setForeground(new java.awt.Color(0, 0, 0));
        jTextField15.setBorder(null);
        pnlRestock.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 370, 20));

        jTextField14.setBackground(new java.awt.Color(255, 255, 255));
        jTextField14.setForeground(new java.awt.Color(0, 0, 0));
        jTextField14.setBorder(null);
        pnlRestock.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 370, -1));

        jTextField13.setBackground(new java.awt.Color(255, 255, 255));
        jTextField13.setForeground(new java.awt.Color(0, 0, 0));
        jTextField13.setBorder(null);
        pnlRestock.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 370, 20));

        jTextField12.setBackground(new java.awt.Color(255, 255, 255));
        jTextField12.setForeground(new java.awt.Color(0, 0, 0));
        jTextField12.setBorder(null);
        pnlRestock.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 370, 20));

        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setForeground(new java.awt.Color(0, 0, 0));
        jTextField11.setBorder(null);
        pnlRestock.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 370, -1));

        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setForeground(new java.awt.Color(0, 0, 0));
        jTextField10.setBorder(null);
        pnlRestock.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 370, -1));

        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setForeground(new java.awt.Color(0, 0, 0));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField9.setBorder(null);
        pnlRestock.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 370, 100));

        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setForeground(new java.awt.Color(0, 0, 0));
        jTextField8.setBorder(null);
        pnlRestock.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 370, 20));

        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setForeground(new java.awt.Color(0, 0, 0));
        jTextField7.setBorder(null);
        pnlRestock.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 370, -1));

        btnBack.setText("-");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlRestock.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 740, 130, 30));

        btnAddStock1.setText("-");
        btnAddStock1.setBorderPainted(false);
        btnAddStock1.setContentAreaFilled(false);
        pnlRestock.add(btnAddStock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 743, 130, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Restock.png"))); // NOI18N
        jLabel21.setToolTipText("");
        pnlRestock.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        pnlProduct.add(pnlRestock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrDel.setBackground(new java.awt.Color(255, 255, 255));
        btnPrDel.setText("-");
        btnPrDel.setBorder(null);
        btnPrDel.setBorderPainted(false);
        btnPrDel.setContentAreaFilled(false);
        jPanel7.add(btnPrDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 740, 80, 30));

        btnPrRestock.setBackground(new java.awt.Color(255, 255, 255));
        btnPrRestock.setText("-");
        btnPrRestock.setBorder(null);
        btnPrRestock.setBorderPainted(false);
        btnPrRestock.setContentAreaFilled(false);
        btnPrRestock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrRestockActionPerformed(evt);
            }
        });
        jPanel7.add(btnPrRestock, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 740, 80, 30));

        btnAddProduct.setBackground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("-");
        btnAddProduct.setBorder(null);
        btnAddProduct.setBorderPainted(false);
        btnAddProduct.setContentAreaFilled(false);
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        jPanel7.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 740, 160, 30));

        btnPrUpdate1.setBackground(new java.awt.Color(255, 255, 255));
        btnPrUpdate1.setText("-");
        btnPrUpdate1.setBorder(null);
        btnPrUpdate1.setBorderPainted(false);
        btnPrUpdate1.setContentAreaFilled(false);
        jPanel7.add(btnPrUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 740, 80, 30));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);
        jPanel7.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 116, 380, 20));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Name", "Description", "Category", "Stock", "Price", "Supplier", "Status", "Date Add", "Expiration"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 930, 500));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status:", "Available", "Out of Stock", "Discontinued" }));
        jPanel7.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 210, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/AdProduct.png"))); // NOI18N
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, -1));

        pnlProduct.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 790));

        jPanel2.add(pnlProduct, "product");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 1, 1320, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
       setActive("dashboard");
        CardLayout cl = (CardLayout)(jPanel2.getLayout());
            cl.show(jPanel2, "dashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        setActive("users");
        CardLayout cl = (CardLayout)(jPanel2.getLayout());
            cl.show(jPanel2, "users");
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
        setActive("order");
        pnlverufy.setVisible(false);
        pnlView.setVisible(false);
        CardLayout cl = (CardLayout)(jPanel2.getLayout());
            cl.show(jPanel2, "order");
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        setActive("product");
        pnlAddPr.setVisible(false);
        pnlRestock.setVisible(false);
        CardLayout cl = (CardLayout)(jPanel2.getLayout());
            cl.show(jPanel2, "product");
        
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        setActive("supplier");
        pnlAddSuppliers.setVisible(false);
        CardLayout cl = (CardLayout)(jPanel2.getLayout());
            cl.show(jPanel2, "supplier");
    }//GEN-LAST:event_btnSupplierActionPerformed
    private static final System.Logger LOG = System.getLogger(AdminDashboard.class.getName());

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        setActive("reports");
        CardLayout cl = (CardLayout)(jPanel2.getLayout());
            cl.show(jPanel2, "reports");
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        pnlAddPr.setVisible(true);
        pnlProduct.setVisible(false);
        pnlRestock.setVisible(false);
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       startUp log = new startUp();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtxAddDescripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtxAddDescripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtxAddDescripActionPerformed

    private void btnSupAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupAddActionPerformed
       pnlAddSuppliers.setVisible(true);
    }//GEN-LAST:event_btnSupAddActionPerformed

    private void btnStaffAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffAddActionPerformed
       pnlAddStaff.setVisible(true);
    }//GEN-LAST:event_btnStaffAddActionPerformed

    private void btnAddCancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCancel2ActionPerformed
        pnlUsers.setVisible(true);
        pnlAddStaff.setVisible(false);
    }//GEN-LAST:event_btnAddCancel2ActionPerformed

    private void btnAddCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCancel1ActionPerformed
        pnlSuppliers.setVisible(true);
        pnlAddSuppliers.setVisible(false);
    }//GEN-LAST:event_btnAddCancel1ActionPerformed

    private void btnAddCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCancelActionPerformed
        pnlAddPr.setVisible(false);
        pnlProduct.setVisible(true);
    }//GEN-LAST:event_btnAddCancelActionPerformed

    private void btnOrdCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdCancActionPerformed
        pnlOrder.setVisible(true);
        pnlverufy.setVisible(false);
    }//GEN-LAST:event_btnOrdCancActionPerformed

    private void btnOrdCanc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdCanc1ActionPerformed
        pnlView.setVisible(false);
        pnlOrder.setVisible(true);
    }//GEN-LAST:event_btnOrdCanc1ActionPerformed

    private void btnStaffAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStaffAdd1ActionPerformed

    private void txtAddName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddName1ActionPerformed

    private void btnOrdVerifyPay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdVerifyPay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrdVerifyPay1ActionPerformed

    private void btnOrdView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdView1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrdView1ActionPerformed

    private void btnOrdViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdViewActionPerformed
        pnlView.setVisible(true);
    }//GEN-LAST:event_btnOrdViewActionPerformed

    private void btnPrRestockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrRestockActionPerformed
        pnlRestock.setVisible(true);
        jPanel7.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_btnPrRestockActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        pnlRestock.setVisible(false);
        jPanel1.setVisible(true);
        jPanel7.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCancel;
    private javax.swing.JButton btnAddCancel1;
    private javax.swing.JButton btnAddCancel2;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAddSave;
    private javax.swing.JButton btnAddSave1;
    private javax.swing.JButton btnAddSave2;
    private javax.swing.JButton btnAddStock1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCusDel;
    private javax.swing.JButton btnCusDel1;
    private javax.swing.JButton btnCusEdit;
    private javax.swing.JButton btnCusEdit1;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrdCanc;
    private javax.swing.JButton btnOrdCanc1;
    private javax.swing.JButton btnOrdConf;
    private javax.swing.JButton btnOrdConf1;
    private javax.swing.JButton btnOrdDel1;
    private javax.swing.JButton btnOrdDel2;
    private javax.swing.JButton btnOrdDel3;
    private javax.swing.JButton btnOrdEdit2;
    private javax.swing.JButton btnOrdEdit3;
    private javax.swing.JButton btnOrdEdit4;
    private javax.swing.JButton btnOrdVerifyPay1;
    private javax.swing.JButton btnOrdView;
    private javax.swing.JButton btnOrdView1;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnPrDel;
    private javax.swing.JButton btnPrRestock;
    private javax.swing.JButton btnPrUpdate1;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnStaffAdd;
    private javax.swing.JButton btnStaffAdd1;
    private javax.swing.JButton btnStaffDel;
    private javax.swing.JButton btnStaffDel1;
    private javax.swing.JButton btnStaffEdit;
    private javax.swing.JButton btnStaffEdit1;
    private javax.swing.JButton btnSupAdd;
    private javax.swing.JButton btnSupDel;
    private javax.swing.JButton btnSupEdit;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btnUsers;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblLowStiock;
    private javax.swing.JLabel lblTotalCustomer;
    private javax.swing.JLabel lblTotalOrd;
    private javax.swing.JLabel lblTotalSales;
    private javax.swing.JLabel lblTransComp;
    private javax.swing.JLabel lblTransPend;
    private javax.swing.JPanel pnlAddPr;
    private javax.swing.JPanel pnlAddStaff;
    private javax.swing.JPanel pnlAddSuppliers;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JPanel pnlProduct;
    private javax.swing.JPanel pnlReports;
    private javax.swing.JPanel pnlRestock;
    private javax.swing.JPanel pnlSuppliers;
    private javax.swing.JPanel pnlUsers;
    private javax.swing.JPanel pnlUsers1;
    private javax.swing.JPanel pnlUsers2;
    private javax.swing.JPanel pnlView;
    private javax.swing.JPanel pnlverufy;
    private javax.swing.JTextField txtAddCategory;
    private javax.swing.JTextField txtAddName;
    private javax.swing.JTextField txtAddName1;
    private javax.swing.JTextField txtAddName2;
    private javax.swing.JTextField txtAddPrice;
    private javax.swing.JTextField txtAddStock;
    private javax.swing.JTextField txtAddSupCN;
    private javax.swing.JTextField txtAddSupCP;
    private javax.swing.JTextField txtAddSupCP1;
    private javax.swing.JTextField txtAddSupEm;
    private javax.swing.JTextField txtAddSupEm1;
    private javax.swing.JTextField txtxAddDescrip;
    // End of variables declaration//GEN-END:variables
}
