/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adsfinalproject;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;

/**
 *
 * @author kleir
 */

public class startUp extends javax.swing.JFrame {
    String selectedRole = "";
    ImageIcon cs, st, ad;
    ImageIcon csd, std, add;
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(startUp.class.getName());

    /**
     * Creates new form Welcome
     */
    public startUp() {
        initComponents();
        setSize(1318, 847);
        setLocationRelativeTo(null);
        btnLogin.setContentAreaFilled(false);
        btnRegister.setContentAreaFilled(false);
        btnLOg.setContentAreaFilled(false);
        btnBackLog.setContentAreaFilled(false);
        btnBackLog1.setContentAreaFilled(false);
        btnregConfirm.setContentAreaFilled(false);
        btnLogStaff.setContentAreaFilled(false);
        btnLogCustomer.setContentAreaFilled(false);
        btnLogAdmin.setContentAreaFilled(false);
        btnBackReg.setContentAreaFilled(false);
        

        //===/
        pnlLog.setVisible(false);
        pnlReg.setVisible(false);
        pnlUserChoice.setVisible(false);
        
        //====/
        cs = new ImageIcon(getClass().getResource("/design/cus.png"));
        csd = new ImageIcon(getClass().getResource("/design/cusd.png"));
        st = new ImageIcon(getClass().getResource("/design/staff.png"));
        std = new ImageIcon(getClass().getResource("/design/staffd.png"));
        ad = new ImageIcon(getClass().getResource("/design/logadmin.png"));
        add = new ImageIcon(getClass().getResource("/design/admind.png"));
    }
    private void setRole(String role){
        selectedRole = role;
        
        btnLogCustomer.setIcon(cs);
        btnLogStaff.setIcon(st);
        btnLogAdmin.setIcon(ad);
        
        if(role.equals("customer")){
            btnLogCustomer.setIcon(csd);
        }else if (role.equals("staff")){
            btnLogStaff.setIcon(std);
        }else if(role.equals("admin")){
            btnLogAdmin.setIcon(add);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlLog = new javax.swing.JPanel();
        btnBackLog = new javax.swing.JButton();
        btnLOg = new javax.swing.JButton();
        txtLogEmail = new javax.swing.JTextField();
        txtLogPass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pnlReg = new javax.swing.JPanel();
        btnRegNext = new javax.swing.JButton();
        btnBackReg = new javax.swing.JButton();
        txtRegPass = new javax.swing.JTextField();
        txtRegEmail = new javax.swing.JTextField();
        txtRegName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        log1 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlUserChoice = new javax.swing.JPanel();
        btnLogAdmin = new javax.swing.JButton();
        btnLogStaff = new javax.swing.JButton();
        btnLogCustomer = new javax.swing.JButton();
        btnregConfirm = new javax.swing.JButton();
        btnBackLog1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLog.setBackground(new java.awt.Color(255, 255, 255));
        pnlLog.setFocusable(false);
        pnlLog.setPreferredSize(new java.awt.Dimension(1300, 800));
        pnlLog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackLog.setForeground(new java.awt.Color(0, 0, 0));
        btnBackLog.setText("-");
        btnBackLog.setBorder(null);
        btnBackLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLogActionPerformed(evt);
            }
        });
        pnlLog.add(btnBackLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, 80, 60));

        btnLOg.setForeground(new java.awt.Color(0, 0, 0));
        btnLOg.setText("-");
        btnLOg.setBorder(null);
        btnLOg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOgActionPerformed(evt);
            }
        });
        pnlLog.add(btnLOg, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 220, 70));

        txtLogEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtLogEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtLogEmail.setBorder(null);
        pnlLog.add(txtLogEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 410, 40));

        txtLogPass.setBackground(new java.awt.Color(255, 255, 255));
        txtLogPass.setForeground(new java.awt.Color(0, 0, 0));
        txtLogPass.setBorder(null);
        pnlLog.add(txtLogPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 410, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Login 2.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlLog.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        jPanel1.add(pnlLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 810));

        pnlReg.setPreferredSize(new java.awt.Dimension(1300, 800));
        pnlReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegNext.setForeground(new java.awt.Color(0, 0, 0));
        btnRegNext.setText("-");
        btnRegNext.setBorder(null);
        btnRegNext.setBorderPainted(false);
        btnRegNext.setContentAreaFilled(false);
        btnRegNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegNextActionPerformed(evt);
            }
        });
        pnlReg.add(btnRegNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 400, 70));

        btnBackReg.setForeground(new java.awt.Color(0, 0, 0));
        btnBackReg.setText("-");
        btnBackReg.setBorder(null);
        btnBackReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRegActionPerformed(evt);
            }
        });
        pnlReg.add(btnBackReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 670, 80, 60));

        txtRegPass.setBackground(new java.awt.Color(255, 255, 255));
        txtRegPass.setForeground(new java.awt.Color(0, 0, 0));
        txtRegPass.setBorder(null);
        pnlReg.add(txtRegPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 410, 40));

        txtRegEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtRegEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtRegEmail.setBorder(null);
        pnlReg.add(txtRegEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 410, 30));

        txtRegName.setBackground(new java.awt.Color(255, 255, 255));
        txtRegName.setForeground(new java.awt.Color(0, 0, 0));
        txtRegName.setBorder(null);
        pnlReg.add(txtRegName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 312, 410, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Register.png"))); // NOI18N
        pnlReg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(pnlReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        log1.setBackground(new java.awt.Color(204, 204, 204));
        log1.setPreferredSize(new java.awt.Dimension(1300, 800));
        log1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("-");
        btnRegister.setBorder(null);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        log1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 670, 390, 80));

        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("-");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        log1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 390, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Login 1.png"))); // NOI18N
        log1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        jPanel1.add(log1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        pnlUserChoice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogAdmin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/logadmin.png"))); // NOI18N
        btnLogAdmin.setText("-");
        btnLogAdmin.setBorder(null);
        btnLogAdmin.setBorderPainted(false);
        btnLogAdmin.setContentAreaFilled(false);
        btnLogAdmin.setFocusPainted(false);
        btnLogAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogAdminActionPerformed(evt);
            }
        });
        pnlUserChoice.add(btnLogAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 180, 150));

        btnLogStaff.setForeground(new java.awt.Color(0, 0, 0));
        btnLogStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/staff.png"))); // NOI18N
        btnLogStaff.setText("-");
        btnLogStaff.setBorder(null);
        btnLogStaff.setBorderPainted(false);
        btnLogStaff.setContentAreaFilled(false);
        btnLogStaff.setFocusPainted(false);
        btnLogStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogStaffActionPerformed(evt);
            }
        });
        pnlUserChoice.add(btnLogStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 180, 150));

        btnLogCustomer.setForeground(new java.awt.Color(0, 0, 0));
        btnLogCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/cus.png"))); // NOI18N
        btnLogCustomer.setText("-");
        btnLogCustomer.setBorder(null);
        btnLogCustomer.setContentAreaFilled(false);
        btnLogCustomer.setFocusPainted(false);
        btnLogCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogCustomerActionPerformed(evt);
            }
        });
        pnlUserChoice.add(btnLogCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 190, 150));

        btnregConfirm.setForeground(new java.awt.Color(0, 0, 0));
        btnregConfirm.setText("-");
        btnregConfirm.setBorder(null);
        btnregConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregConfirmActionPerformed(evt);
            }
        });
        pnlUserChoice.add(btnregConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 513, 330, 70));

        btnBackLog1.setForeground(new java.awt.Color(0, 0, 0));
        btnBackLog1.setText("-");
        btnBackLog1.setBorder(null);
        btnBackLog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLog1ActionPerformed(evt);
            }
        });
        pnlUserChoice.add(btnBackLog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, 80, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Login 3.png"))); // NOI18N
        pnlUserChoice.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(pnlUserChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 810));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
      pnlLog.setVisible(true);
      log1.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        pnlReg.setVisible(true);
        log1.setVisible(false);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLOgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOgActionPerformed
       String email = txtLogEmail.getText().trim();
    String password = txtLogPass.getText().trim();

    if (email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Fill all fields");
        return;
    }

    try {

        Connection con = DBConnection.getConnection();

        String sql = "SELECT * FROM users WHERE email=? AND password=?";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, email);
        pst.setString(2, password);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            String role = rs.getString("role");

            JOptionPane.showMessageDialog(null, "Login successful!");

            JFrame dashboard;

            if (role.equals("admin")) {
                dashboard = new AdminDashboard();
            } else if (role.equals("staff")) {
                dashboard = new EmployeeDashboard();
            } else {
                dashboard = new CustomerDashboard();
            }

            dashboard.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Invalid email or password");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }

    }//GEN-LAST:event_btnLOgActionPerformed

    private void btnBackLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLogActionPerformed
        pnlLog.setVisible(false);
        log1.setVisible(true);
    }//GEN-LAST:event_btnBackLogActionPerformed

    private void btnBackLog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLog1ActionPerformed
        pnlReg.setVisible(true);
        
    }//GEN-LAST:event_btnBackLog1ActionPerformed

    private void btnregConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregConfirmActionPerformed
Connection con = DBConnection.getConnection();

    try {
        String username = txtRegName.getText();
        String email = txtRegEmail.getText();
        String pass = txtRegPass.getText();

        // check if role selected
        if (selectedRole.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select account type!");
            return;
        }

        if (username.isEmpty() || email.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all fields!");
            return;
        }

        // 🔍 CHECK IF USER EXISTS
        PreparedStatement check = con.prepareStatement(
            "SELECT * FROM users WHERE username=? OR email=?"
        );
        check.setString(1, username);
        check.setString(2, email);
        ResultSet rs = check.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "Account already exists!");
            return;
        }

        // ✅ INSERT USER
        PreparedStatement pst = con.prepareStatement(
            "INSERT INTO users(username, email, password, role) VALUES (?, ?, ?, ?)"
        );

        pst.setString(1, username);
        pst.setString(2, email);
        pst.setString(3, pass);
        pst.setString(4, selectedRole); // 🔥 use selected role

        int result = pst.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(null, "Registered Successfully!");

            txtRegName.setText("");
            txtRegEmail.setText("");
            txtRegPass.setText("");

            pnlReg.setVisible(false);
            pnlLog.setVisible(true);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }

    }//GEN-LAST:event_btnregConfirmActionPerformed

    private void btnLogCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogCustomerActionPerformed
        setRole("customer");
    }//GEN-LAST:event_btnLogCustomerActionPerformed

    private void btnLogStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogStaffActionPerformed
        setRole("staff");
    }//GEN-LAST:event_btnLogStaffActionPerformed

    private void btnLogAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogAdminActionPerformed
        setRole("admin");
    }//GEN-LAST:event_btnLogAdminActionPerformed

    private void btnBackRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRegActionPerformed
        pnlReg.setVisible(false);
        log1.setVisible(true);
    }//GEN-LAST:event_btnBackRegActionPerformed

    private void btnRegNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegNextActionPerformed
       
    String username = txtRegName.getText();
    String email = txtRegEmail.getText();
    String pass = txtRegPass.getText();

    if (username.isEmpty() || email.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill all fields first!");
        return;
    }

    pnlUserChoice.setVisible(true);
    pnlReg.setVisible(false);
    
    }//GEN-LAST:event_btnRegNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new startUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackLog;
    private javax.swing.JButton btnBackLog1;
    private javax.swing.JButton btnBackReg;
    private javax.swing.JButton btnLOg;
    private javax.swing.JButton btnLogAdmin;
    private javax.swing.JButton btnLogCustomer;
    private javax.swing.JButton btnLogStaff;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegNext;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnregConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel log1;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlReg;
    private javax.swing.JPanel pnlUserChoice;
    private javax.swing.JTextField txtLogEmail;
    private javax.swing.JTextField txtLogPass;
    private javax.swing.JTextField txtRegEmail;
    private javax.swing.JTextField txtRegName;
    private javax.swing.JTextField txtRegPass;
    // End of variables declaration//GEN-END:variables
}
